// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW-mwylO7IRw2e4k29IVZnemCndKzZ7GU',
    appId: '1:526428191351:web:f97af4c4c00b0244cea472',
    messagingSenderId: '526428191351',
    projectId: 'chatty-app-f3921',
    authDomain: 'chatty-app-f3921.firebaseapp.com',
    storageBucket: 'chatty-app-f3921.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd6s_M0XgoHvlQr7lSehY6vQD1kX2qBuY',
    appId: '1:526428191351:android:57cc4c952c5b0d1bcea472',
    messagingSenderId: '526428191351',
    projectId: 'chatty-app-f3921',
    storageBucket: 'chatty-app-f3921.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcKMtxOvwdafclrjuwNC8FeyJ5_A-59ow',
    appId: '1:526428191351:ios:104c2c65ca216757cea472',
    messagingSenderId: '526428191351',
    projectId: 'chatty-app-f3921',
    storageBucket: 'chatty-app-f3921.appspot.com',
    iosClientId: '526428191351-qdk234jmceuctade51k2i2hcro5u8j4j.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcKMtxOvwdafclrjuwNC8FeyJ5_A-59ow',
    appId: '1:526428191351:ios:104c2c65ca216757cea472',
    messagingSenderId: '526428191351',
    projectId: 'chatty-app-f3921',
    storageBucket: 'chatty-app-f3921.appspot.com',
    iosClientId: '526428191351-qdk234jmceuctade51k2i2hcro5u8j4j.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattyApp',
  );
}
